[project]
name = "crypto-ask-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.0",
    "scrapy>=2.12.0",
    "sentence-transformers>=4.0.2",
    "tqdm>=4.67.1",
]
